<?php

declare(strict_types=1);

namespace SlopScan\Tests;

use PHPUnit\Framework\TestCase;
use SlopScan\Review\PhpStanBaseline;
use SlopScan\Review\PhpStanBaselineGrowth;

final class PhpStanBaselineGrowthTest extends TestCase
{
    /** @var list<string> */
    private array $directories = [];

    protected function tearDown(): void
    {
        foreach ($this->directories as $directory) {
            $this->remove($directory);
        }
    }

    public function testReportsOneSourcePathThatGainedEntries(): void
    {
        $findings = $this->compare(
            $this->baseline(['src/Foo.php' => 1]),
            $this->baseline(['src/Foo.php' => 3]),
        );

        self::assertCount(1, $findings);
        self::assertSame('php.static-analysis-baseline-growth', $findings[0]->ruleId);
        self::assertSame('src/Foo.php', $findings[0]->path);
        self::assertContains('added-entries=2', $findings[0]->evidence);
        self::assertContains('baseline=phpstan-baseline.neon', $findings[0]->evidence);
        self::assertContains('source=src/Foo.php', $findings[0]->evidence);
        self::assertContains('baseline-introduced=false', $findings[0]->evidence);
    }

    public function testReportsEachGrowingSourcePathAndIgnoresUnchangedOnes(): void
    {
        $findings = $this->compare(
            $this->baseline(['src/A.php' => 1, 'src/B.php' => 2, 'src/C.php' => 1]),
            $this->baseline(['src/A.php' => 2, 'src/B.php' => 2, 'src/C.php' => 1, 'src/D.php' => 4]),
        );

        $sources = array_map(static fn ($finding): ?string => $finding->path, $findings);
        sort($sources);
        self::assertSame(['src/A.php', 'src/D.php'], $sources);
    }

    public function testFindingFallsBackToTheBaselineFileWhenTheSourceFileIsGone(): void
    {
        $base = $this->tree(['phpstan-baseline.neon' => $this->baseline(['src/Gone.php' => 1])]);
        $head = $this->tree(['phpstan-baseline.neon' => $this->baseline(['src/Gone.php' => 2])]);

        $findings = PhpStanBaselineGrowth::comparePaths($base, $head);

        self::assertCount(1, $findings);
        self::assertSame('phpstan-baseline.neon', $findings[0]->path);
        self::assertContains('source=src/Gone.php', $findings[0]->evidence);
    }

    public function testRegeneratedBaselineWithSameEffectiveEntriesStaysQuiet(): void
    {
        $before = $this->baseline(['src/A.php' => 2, 'src/B.php' => 1]);
        // Reordered, and one count split into two entries: same effective suppression.
        $after = "parameters:\n\tignoreErrors:\n"
            . "\t\t-\n\t\t\tmessage: '#^B$#'\n\t\t\tpath: src/B.php\n"
            . "\t\t-\n\t\t\tmessage: '#^A one$#'\n\t\t\tpath: src/A.php\n"
            . "\t\t-\n\t\t\tmessage: '#^A two$#'\n\t\t\tpath: src/A.php\n";

        self::assertSame([], $this->compare($before, $after));
    }

    public function testShrinkingBaselineStaysQuiet(): void
    {
        self::assertSame([], $this->compare(
            $this->baseline(['src/A.php' => 3, 'src/B.php' => 1]),
            $this->baseline(['src/A.php' => 1]),
        ));
    }

    public function testNewlyIntroducedBaselineIsOneExplicitFinding(): void
    {
        $findings = $this->compare(null, $this->baseline(['src/A.php' => 2, 'src/B.php' => 1]));

        self::assertCount(1, $findings);
        self::assertSame('phpstan-baseline.neon', $findings[0]->path);
        self::assertContains('baseline-introduced=true', $findings[0]->evidence);
        self::assertContains('added-entries=3', $findings[0]->evidence);
        self::assertStringContainsString('accepts 3 existing PHPStan errors', $findings[0]->message);
    }

    public function testMalformedBaselineFailsExplicitlyInsteadOfReadingAsNoGrowth(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Unsupported PHPStan baseline');

        $this->compare($this->baseline(['src/A.php' => 1]), "this is not a baseline\n");
    }

    public function testEntryWithoutPathFailsExplicitly(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('an entry has no "path"');

        $this->compare(
            $this->baseline(['src/A.php' => 1]),
            "parameters:\n\tignoreErrors:\n\t\t-\n\t\t\tmessage: '#^x$#'\n\t\t\tcount: 1\n",
        );
    }

    public function testFilesWithoutABaselineAreIgnored(): void
    {
        self::assertSame([], $this->compare(null, null));
    }

    public function testParserHandlesQuotingCountsPlaceholdersAndEmptyLists(): void
    {
        $contents = <<<'NEON'
# generated by PHPStan
parameters:
	ignoreErrors:
		-
			message: '#^Call to a method''s thing\.$#'
			identifier: method.notFound
			count: 2
			path: ../src/Foo.php

		- message: "#^x$#"
		  path: %rootDir%/../../../src/Bar.php
NEON;

        self::assertSame(
            ['src/Bar.php' => 1, 'src/Foo.php' => 2],
            PhpStanBaseline::countsByPath($contents, 'config'),
        );
        self::assertSame([], PhpStanBaseline::countsByPath("parameters:\n\tignoreErrors: []\n", ''));
    }

    public function testParserSkipsMultiLineRawMessageBlocks(): void
    {
        $contents = "parameters:\n\tignoreErrors:\n\t\t-\n\t\t\trawMessage: '''\n"
            . "\t\t\t\tFirst line: with a colon\n\t\t\t\t- and a dash\n\t\t\t'''\n"
            . "\t\t\tidentifier: classConstant.deprecatedClass\n\t\t\tcount: 2\n\t\t\tpath: ../src/ProfileList.php\n";

        self::assertSame(['src/ProfileList.php' => 2], PhpStanBaseline::countsByPath($contents, 'devTools'));
    }

    public function testUnterminatedMultiLineBlockFailsExplicitly(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('unterminated multi-line string');

        PhpStanBaseline::countsByPath("parameters:\n\tignoreErrors:\n\t\t-\n\t\t\trawMessage: '''\n\t\t\t\tnever closed\n", '');
    }

    public function testBaselineIncludedFromPhpStanConfigIsDiscovered(): void
    {
        $base = $this->tree(['phpstan.neon' => "includes:\n\t- phpstan-baseline-level5.neon\n"]);
        $head = $this->tree([
            'phpstan.neon' => "includes:\n\t- phpstan-baseline-level5.neon\n",
            'phpstan-baseline-level5.neon' => $this->baseline(['src/A.php' => 1]),
        ]);

        $findings = PhpStanBaselineGrowth::comparePaths($base, $head);

        self::assertCount(1, $findings);
        self::assertContains('baseline=phpstan-baseline-level5.neon', $findings[0]->evidence);
    }

    /** @return list<\SlopScan\Model\Finding> */
    private function compare(?string $before, ?string $after): array
    {
        $sources = ['src/A.php' => '<?php', 'src/B.php' => '<?php', 'src/C.php' => '<?php', 'src/D.php' => '<?php', 'src/Foo.php' => '<?php'];
        $base = $this->tree($before === null ? [] : ['phpstan-baseline.neon' => $before] + $sources);
        $head = $this->tree($after === null ? [] : ['phpstan-baseline.neon' => $after] + $sources);

        return PhpStanBaselineGrowth::comparePaths($base, $head);
    }

    /** @param array<string,int> $counts */
    private function baseline(array $counts): string
    {
        $neon = "parameters:\n\tignoreErrors:\n";
        foreach ($counts as $path => $count) {
            $neon .= "\t\t-\n\t\t\tmessage: '#^Some error\\.$#'\n\t\t\tcount: {$count}\n\t\t\tpath: {$path}\n";
        }

        return $neon;
    }

    /** @param array<string,string> $files */
    private function tree(array $files): string
    {
        $directory = sys_get_temp_dir() . '/slop-scan-baseline-' . bin2hex(random_bytes(4));
        mkdir($directory, 0777, true);
        $this->directories[] = $directory;
        foreach ($files as $name => $contents) {
            if (!is_dir(dirname($directory . '/' . $name))) {
                mkdir(dirname($directory . '/' . $name), 0777, true);
            }
            file_put_contents($directory . '/' . $name, $contents);
        }

        return $directory;
    }

    private function remove(string $path): void
    {
        if (is_file($path)) {
            unlink($path);
            return;
        }

        foreach (scandir($path) ?: [] as $item) {
            if ($item !== '.' && $item !== '..') {
                $this->remove($path . '/' . $item);
            }
        }
        rmdir($path);
    }
}
