<?php

declare(strict_types=1);

namespace SlopScan\Rule;

use SlopScan\Model\Finding;
use SlopScan\Runtime\ProviderContext;

final class PlaceholderCommentsRule extends BaseRule
{
    public function id(): string { return 'php.placeholder-comments'; }
    public function family(): string { return 'comments'; }
    public function severity(): string { return 'weak'; }
    public function scope(): string { return 'file'; }
    public function requires(): array { return ['file.comments']; }

    public function evaluate(ProviderContext $context): array
    {
        $findings = [];
        foreach ($context->runtime->store->getFileFact($context->file->path, 'file.comments') ?? [] as $comment) {
            if (preg_match('/\b(todo|fixme|hack|placeholder|temporary|generated by ai)\b/i', $comment['text'])) {
                $findings[] = new Finding($this->id(), $this->family(), $this->severity(), 'file', 'Found placeholder-style PHP comment', [trim($comment['text'])], 0.5, [['path' => $context->file->path, 'line' => $comment['line'], 'column' => 1]], $context->file->path);
            }
        }
        return $findings;
    }
}
