<?php

declare(strict_types=1);

namespace SlopScan\Rule;

use SlopScan\Model\Finding;
use SlopScan\Runtime\ProviderContext;

final class PlaceholderCommentsRule extends BaseRule
{
    public function id(): string { return 'php.placeholder-comments'; }
    public function family(): string { return 'comments'; }
    public function severity(): string { return 'weak'; }
    public function scope(): string { return 'file'; }
    public function requires(): array { return ['file.comments']; }

    private const MARKER = '/\b(todo|fixme|hack|placeholder|temporary|generated by ai)\b/i';
    private const DIRECTIVE = '/^\W*(todo|fixme|hack|xxx)\b/i';
    private const RESOLVED = '/\b(?:resolved|removed|deleted|no longer|already (?:fixed|done|handled|implemented|resolved|removed))\b/i';

    /**
     * Historical prose such as "a resolved TODO docblock is deleted" explains past work;
     * a comment that opens with the marker ("TODO: ...") stays deferred work even when it mentions removal.
     */
    private static function describesResolvedWork(string $text): bool
    {
        return preg_match(self::DIRECTIVE, ltrim($text, "/*# \t\r\n")) !== 1
            && preg_match(self::RESOLVED, $text) === 1;
    }

    public function evaluate(ProviderContext $context): array
    {
        $findings = [];
        foreach ($context->runtime->store->getFileFact($context->file->path, 'file.comments') ?? [] as $comment) {
            if (preg_match(self::MARKER, $comment['text']) && !self::describesResolvedWork($comment['text'])) {
                $findings[] = new Finding($this->id(), $this->family(), $this->severity(), 'file', 'Found placeholder-style PHP comment', [trim($comment['text'])], 0.5, [['path' => $context->file->path, 'line' => $comment['line'], 'column' => 1]], $context->file->path);
            }
        }
        return $findings;
    }
}
